name: Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out inertia
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build inertia
        run: go build -v ./...

      - name: Test inertia
        run: go test -v ./...
